### PR TITLE
Refresh to front page

### PR DESCRIPTION
**Pull request by untitledeveloper**
* Have refreshed the styling on navbar, search box and result cards
* Have resolved result cards doubling issue
* Have put footer in index.html rather than being rendered dynamically
* Unique font for brand

Preview below

webpage_img_1

### CODE REVIEW

**Comment by jsharples777** [comment]
Well these are kind of last minute, but I will let the other team members decide on them.

Some of the changes (footer etc) are in the js not JSX and will be overwritten.

The styling the pagination was round specifically to match the search buttons.

I will let the others chime in

**Review by jsharples777 — COMMENTED** [review]
Aside from disagreeing about the non-rounded pagination buttons and putting the style changes in the right spots (JSX), everything looks quite good when I applied it to my branch

**Comment by AMIrene** [comment]
I like the color changes to the buttons in the search bar container. Very nice! Would be good to keep pagination consistent. Happy to approve as long as Teoman - you are able to do it all and it does not result in extra work for Jim.

**Comment by untitledeveloper** [comment]
After making the changes I checked to see if everything was working. Nothing seems to be broken. I can have a look through it again after work.

**Comment by jsharples777** [comment]
If you check https://group3-recipe-search.herokuapp.com/ the changes are there. I put the styles in the right places for the JSX, moved the footer, (fixed my two bugs), and renamed the styles to match the bulma style naming convention

**Pull request closed without merging**
