### PR TITLE
Notifications with fancy transitions

### PR DESCRIPTION
**Pull request by jsharples777**
My partner used the web site and was a little frustrated with the lack of user feedback with the "add to favourites" and "add to shopping list" and suggested I wrote notifications.

That led to a whole new thing and then they had to stack properly and move when timed out or user deleted.

Anyway, may I present notifications.

### CODE REVIEW

**Review by raven-bootcamp — APPROVED** [review]
Looks excellent, excited to see it in action!

**Comment by jsharples777** [comment]
It's live on Heroku

**Comment by raven-bootcamp** [comment]
> It's live on Heroku

Haha yeah, I realized that the second I wrote it 😅 It seems great!

**Comment by jsharples777** [comment]
Also added
1.  Shopping List - clear list button which clears shopping list and closes the window
2.  Favourites - toggle star outline/filled in for whether recipe in favourites.  User can toggle in recipe search and recipe details.  Deleting from favourite list updates search display (if it was from the last search)
3.  Attribution from EDAMAM, was required per their developer license

**Review by AMIrene — APPROVED** [review]

**Pull request merged**
